export interface Spa {
  id: string;
  slug: string;
  name: string;
  location: string;
  city: string;
  department: "finistere" | "morbihan" | "cotes-d-armor" | "ille-et-vilaine";
  departmentName: string;
  description: string;
  fullDescription: string;
  image: string;
  gallery: string[];
  rating: number;
  reviewCount: number;
  priceRange: string;
  hours: string;
  tags: string[];
  featured: boolean;
  amenities: string[];
  treatments: string[];
  address: string;
  phone: string;
  email: string;
  website: string;
}

export const departments = [
  {
    id: "finistere",
    name: "Finistère",
    description:
      "Au bout du monde, le Finistère offre des spas face à l'océan Atlantique et des soins inspirés par la mer d'Iroise.",
    image: "/images/spa-6.jpg",
  },
  {
    id: "morbihan",
    name: "Morbihan",
    description:
      "Entre golfe et côte sauvage, le Morbihan propose des centres de thalassothérapie renommés et des expériences uniques.",
    image: "/images/spa-1.jpg",
  },
  {
    id: "cotes-d-armor",
    name: "Côtes-d'Armor",
    description:
      "La Côte de Granit Rose et ses paysages exceptionnels inspirent des spas aux soins naturels et authentiques.",
    image: "/images/spa-4.jpg",
  },
  {
    id: "ille-et-vilaine",
    name: "Ille-et-Vilaine",
    description:
      "Des cités corsaires aux forêts légendaires, découvrez des spas alliant patrimoine et bien-être moderne.",
    image: "/images/spa-2.jpg",
  },
];

export const spas: Spa[] = [
  // Finistère
  {
    id: "1",
    slug: "valdys-resort-douarnenez",
    name: "Valdys Resort Douarnenez",
    location: "Douarnenez, Finistère",
    city: "Douarnenez",
    department: "finistere",
    departmentName: "Finistère",
    description:
      "Un concentré de bien-être avec vue plongeante sur la plage des Sables Blancs, offrant des soins d'excellence en thalasso, piscine chauffée et ambiance marine revitalisante.",
    fullDescription:
      "Situé sur la plage des Sables-Blancs, le Valdys Thalasso est un véritable havre de paix surplombant la magnifique baie de Douarnenez. La réception de l'hôtel est ouverte 24h/24. Une salle de sport avec vue sur mer est à votre disposition, ainsi qu'un accès au spa marin.",
    image: "/images/spa-vue-marin.webp",
    gallery: [
      "/images/cabine-lit-hydrorelax.webp",
      "/images/cabine-de-cryotherapie-espace-thalasso-5ee0f936d6da3.webp",
      "/images/riviere-de-marche.jpg",
      "/images/sallederepostisanerie.jpg",
      "/images/bain-hydrommassant.jpg",
    ],
    rating: 3.7,
    reviewCount: 1172,
    priceRange: "€€€",
    hours: "9h - 20h",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
      "Espace tisanerie",
      "Espace detente extérieur",
      "Cabine de cryothérapie",
      "Cabine avec lit hydrorelax",
    ],
    treatments: [
      "Thalassothérapie",
      "Massage",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "42 Bis Rue des Professeurs Curie, 29100 Douarnenez",
    phone: "02 29 20 26 13",
    email: "thalasso.valdysdouarnenez@thalasso.com",
    website: "https://www.thalasso.com/destination/douarnenez",
  },
  {
    id: "2",
    slug: "relais-thalasso-benodet",
    name: "Relais Thalasso Bénodet",
    location: "Bénodet, Finistère",
    city: "Bénodet",
    department: "finistere",
    departmentName: "Finistère",
    description:
      "Spa marin luxueux avec accès direct à la plage, proposant des cures thalasso personnalisées, hammam et vues sur l'océan Atlantique.",
    fullDescription:
      "Situé en bord de mer dans le sud de la Bretagne, le Relais Thalasso de Bénodet vous offre un cadre idyllique pour une pause détente et ressourcement. Dominant l'océan, ce complexe thermal d'eau de mer est ouvert toute l'année et a été entièrement rénové en 2019.",
    image: "/images/relais-thallasso-benodet.webp",
    gallery: ["/images/piscine.webp", "/images/boue-marine-.webp"],
    rating: 4.1,
    reviewCount: 846,
    priceRange: "€€€",
    hours: "9h - 20h",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine d'eau de mer",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Massage",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "Corniche de la Plage, 29950 Bénodet",
    phone: "02 98 66 27 00",
    email: "resa-benodet@relaisthalasso.com",
    website: "https://benodet.relaisthalasso.com/fr",
  },
  {
    id: "3",
    slug: "thalasso-concarneau-spa-marin-resort",
    name: "Thalasso Concarneau Spa Marin Resort",
    location: "Concarneau, Finistère",
    city: "Concarneau",
    department: "finistere",
    departmentName: "Finistère",
    description:
      "Face à une baie magnifique, ce resort combine soins high-tech, piscine vue mer et cuisine locavore.",
    fullDescription:
      "Situé à proximité de la plage des Sables Blancs, le tout nouveau Spa Marin Group HMC Hotels & Resorts offre un cadre privilégié avec de superbes vues sur l'océan tout proche, comme une invitation à la détente et au bien-être.",
    image: "/images/concarneau.webp",
    gallery: [
      "/images/thalasso-concarneau-hotel-and-residence-thalasso-005.webp",
      "/images/thalasso-concarneau-hotel-and-residence-thalasso-017.webp",
      "/images/thalasso-concarneau-hotel-and-residence-environnement-021.webp",
    ],
    rating: 4.4,
    reviewCount: 1620,
    priceRange: "€€€",
    hours: "9h30 - 19h45",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Sauna",
      "Hammam",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Massage", "Thalassothérapie", "Soins visage", "Réflexologie"],
    address: "36 Rue des Sables Blancs, 29900 Concarneau",
    phone: "02 98 75 05 40",
    email: "resort.concarneau@hmc-hotels.com",
    website: "https://www.thalasso-resort-concarneau.com/en",
  },
  {
    id: "4",
    slug: "grand-hotel-des-bains-locquirec-spa-marin",
    name: "Grand Hôtel des Bains Locquirec - Spa Marin",
    location: "Locquirec, Finistère",
    city: "Locquirec",
    department: "finistere",
    departmentName: "Finistère",
    description:
      "Hôtel-spa en bord de mer avec piscine chauffée salée, hammam et soins personnalisés, offrant des vues imprenables sur la baie.",
    fullDescription:
      "Idéalement située entre la magnifique Côte de Granit Rose et la Côte Sauvage, la paisible et pittoresque presqu'île de Locquirec abrite Le Grand Hôtel des Bains, offrant un luxe discret en toutes saisons.",
    image: "/images/1280564.jpg",
    gallery: [
      "/images/grand-hotel-des-bains.jpg",
      "/images/1280565.jpg",
      "/images/1280566.jpg",
    ],
    rating: 4.5,
    reviewCount: 516,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "15 Rue de l'Eglise, 29241 Locquirec",
    phone: "02 98 67 41 02",
    email: "reception@grand-hotel-des-bains.com",
    website: "https://www.grand-hotel-des-bains.com/en",
  },
  {
    id: "5",
    slug: "hotel-brittany-spa-roscoff",
    name: "Hôtel Brittany & Spa Roscoff",
    location: "Roscoff, Finistère",
    city: "Roscoff",
    department: "finistere",
    departmentName: "Finistère",
    description:
      "Spa marin Thalion avec vue sur l'océan, hammam et soins revigorants inspirés de la mer.",
    fullDescription:
      "A 4-star hotel by the sea in Roscoff, Brittany, with Marine Spa, Loïc Le Bail's Michelin-starred Restaurant & Bistrot-Bar.",
    image: "/images/brittany.webp",
    gallery: [
      "/images/2020-09-13.webp",
      "/images/spa-brittany-bretagne-thalion-piscine-733x1100.webp",
      "/images/spa-brittany-bretagne-thalion-salle-de-soins.webp",
    ],
    rating: 4.6,
    reviewCount: 467,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "Boulevard Sainte-Barbe, 29680 Roscoff",
    phone: "02 98 69 70 78",
    email: "contact@hotel-brittany.com",
    website: "https://www.hotel-brittany.com/en",
  },
  // Morbihan
  {
    id: "6",
    slug: "miramar-la-cigale-hotel-thalasso-spa",
    name: "Miramar La Cigale Hôtel Thalasso & Spa",
    location: "Arzon, Morbihan",
    city: "Arzon",
    department: "morbihan",
    departmentName: "Morbihan",
    description:
      "Architecture comme un paquebot luxueux face au Golfe du Morbihan, avec spa marin géant, bains à bulles et vues panoramiques.",
    fullDescription:
      "Entre une piscine d'eau de mer chauffée et un jacuzzi, une salle de sport high-tech avec vue sur l'océan Atlantique, un bar à cocktails et des repas gastronomiques situés au dernier étage du plus bel hôtel du sud de la Bretagne.",
    image: "/images/miramar.webp",
    gallery: [
      "/images/miraamar-piscine.webp",
      "/images/2020-11-04.webp",
      "/images/thumb_2562_480x550_big.jpeg",
    ],
    rating: 4.4,
    reviewCount: 1849,
    priceRange: "€€€",
    hours: "8h30 - 18h30",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine d'eau de mer",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Enveloppement algues",
      "Massage relaxant",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "Port du Crouesty, 56640 Arzon",
    phone: "02 97 53 49 00",
    email: "reservation@miramar-lacigale.com",
    website: "https://miramar-lacigale.com/en",
  },
  {
    id: "7",
    slug: "sofitel-quiberon-thalassa-sea-spa",
    name: "Sofitel Quiberon Thalassa Sea & Spa",
    location: "Quiberon, Morbihan",
    city: "Quiberon",
    department: "morbihan",
    departmentName: "Morbihan",
    description:
      "Institut thalasso de référence avec piscine vue océan, soins innovants et ambiance chic.",
    fullDescription:
      "Situé en Bretagne Sud, au cœur d'un cadre naturel sauvage et magnifique, le Sofitel Quiberon Thalassa sea & spa propose des séjours relaxants dans un cadre exceptionnel.",
    image: "/images/aja_p_6228-17_6by5.webp",
    gallery: [
      "/images/aja_p_6302-85_6by5.webp",
      "/images/ParcoursMarin1.webp",
      "/images/2024-11-20.webp",
    ],
    rating: 4.3,
    reviewCount: 1850,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine d'eau de mer",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Enveloppement algues",
      "Massage relaxant",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "Boulevard Louison Bobet, 56170 Quiberon",
    phone: "02 97 50 20 00",
    email: "H0557-RE@sofitel.com",
    website: "https://www.sofitel-quiberon-thalassa.com/en",
  },
  {
    id: "8",
    slug: "castel-clara-thalasso-spa",
    name: "Castel Clara Thalasso & Spa",
    location: "Bangor, Morbihan",
    city: "Bangor",
    department: "morbihan",
    departmentName: "Morbihan",
    description:
      "Sur la côte sauvage de Belle-Île-en-Mer, avec vues cliffside époustouflantes, spa de 1000 m² et soins marins.",
    fullDescription:
      "Faites une pause face à l'océan. Soins, cures et moments de détente : notre centre de thalassothérapie et spa vous offre un instant de bien-être absolu.",
    image: "/images/2024-07-04.webp",
    gallery: [],
    rating: 4.5,
    reviewCount: 1060,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Enveloppement algues",
      "Massage relaxant",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "Port Goulphar, 56360 Bangor",
    phone: "02 97 31 84 21",
    email: "reservation.cc@castel-clara.com",
    website: "https://www.castel-clara.com/en",
  },
  {
    id: "9",
    slug: "domaine-de-rochevilaine",
    name: "Domaine de Rochevilaine",
    location: "Billiers, Morbihan",
    city: "Billiers",
    department: "morbihan",
    departmentName: "Morbihan",
    description:
      "Hôtel-spa avec complexe aquatique de 1300 m², vue sur l'estuaire de la Vilaine et soins balnéo premium.",
    fullDescription:
      "Le centre de spa vous offre la possibilité de découvrir une gamme de soins revitalisants de haute qualité, une ambiance intimiste et des produits de luxe lors d'une pause bien-être relaxante au bord de l'estuaire de la Vilaine, dans le Morbihan, en Bretagne méridionale.",
    image: "/images/4238594-1411233_0_212_4724_2877_1500_913.jpg",
    gallery: [
      "/images/rochevilaine.webp",
      "/images/rochevilaine-iscine.webp",
      "/images/rochevilaine-outside.webp",
    ],
    rating: 4.7,
    reviewCount: 1587,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Enveloppement algues",
      "Massage relaxant",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "Pointe de Pen Lan, 56190 Billiers",
    phone: "02 97 41 61 61",
    email: "rochevilaine@relaischateaux.com",
    website: "https://www.domainerochevilaine.com/en",
  },
  {
    id: "10",
    slug: "le-celtique-spa-carnac",
    name: "Le Celtique & Spa Carnac",
    location: "Carnac, Morbihan",
    city: "Carnac",
    department: "morbihan",
    departmentName: "Morbihan",
    description:
      "Spa élégant avec piscine chauffée, hammam et soins Phytomer, près des plages.",
    fullDescription:
      "L'hôtel compte désormais 53 chambres et suites, un restaurant, un bar, une piscine intérieure chauffée, un spa et des salles de réunion.",
    image: "/images/spa-carnac.webp",
    gallery: [
      "/images/piscine-carnac.webp",
      "/images/sauna-carnac.webp",
      "/images/le-celtique-spa-carnac-3.webp",
    ],
    rating: 4.5,
    reviewCount: 1900,
    priceRange: "€€",
    hours: "",
    tags: ["Piscine", "Yoga", "Traditions celtiques"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Sauna",
      "Espace relaxation",
      "Jardin zen",
      "Parking",
    ],
    treatments: [
      "Massage pierres chaudes",
      "Rituel celtique",
      "Soin visage",
      "Réflexologie",
      "Yoga",
    ],
    address: "82 Avenue des Druides, 56340 Carnac",
    phone: "02 97 52 14 15",
    email: "",
    website: "https://www.hotel-celtique.com/en",
  },
  // Côtes-d'Armor
  {
    id: "11",
    slug: "spa-marin-du-val-andre",
    name: "Spa Marin du Val André",
    location: "Pléneuf-Val-André, Côtes-d'Armor",
    city: "Pléneuf-Val-André",
    department: "cotes-d-armor",
    departmentName: "Côtes-d'Armor",
    description:
      "Resort 4 étoiles avec thalasso-spa de 2000 m², bassin hydro-actif vue mer et soins high-tech.",
    fullDescription:
      "Le SPA Marin du Val André est un hôtel-spa de luxe situé au cœur des Côtes d'Armor, à Pléneuf Val André, et offrant une vue imprenable sur la mer.",
    image: "/images/2023-02-17.webp",
    gallery: ["/images/YG_L5293.webp", "/images/YG_L5308.webp"],
    rating: 4.4,
    reviewCount: 1583,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "43 Rue Charles de Gannes, 22370 Pléneuf-Val-André",
    phone: "02 56 57 50 02",
    email: "spamarin.valandre.spa@hmc-hotels.com",
    website: "https://www.thalasso-resort-bretagne.com/en",
  },
  {
    id: "12",
    slug: "roz-marine-thalasso-perros-guirec",
    name: "Roz Marine Thalasso Perros-Guirec",
    location: "Perros-Guirec, Côtes-d'Armor",
    city: "Perros-Guirec",
    department: "cotes-d-armor",
    departmentName: "Côtes-d'Armor",
    description:
      "Face à la plage de Trestraou, avec 7000 m² de bien-être, piscine marine et ambiance familiale chic.",
    fullDescription:
      "Offrez-vous un séjour bien-être unique pour revitaliser corps et esprit. Réservez à Roz Marine Hotel Thalasso & Spa, votre destination Thalasso Bretagne à Perros-Guirec.",
    image: "/images/roz_marine_parcours_marin-9.webp",
    gallery: [
      "/images/roz_marine_parcours_marin-4.webp",
      "/images/perros.webp",
      "/images/bein-perros.webp",
    ],
    rating: 4.6,
    reviewCount: 945,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "58 Boulevard de la Mer, 22700 Perros-Guirec",
    phone: "02 57 63 02 22",
    email: "resa@roz-marine-thalasso.com",
    website: "https://roz-marine-thalasso.com/",
  },
  {
    id: "13",
    slug: "agapa-hotel-spa-perros-guirec",
    name: "Agapa Hôtel Spa Perros-Guirec",
    location: "Perros-Guirec, Côtes-d'Armor",
    city: "Perros-Guirec",
    department: "cotes-d-armor",
    departmentName: "Côtes-d'Armor",
    description:
      "Spa Codage avec vue sur l'Archipel des 7 Îles, hammam et soins personnalisés.",
    fullDescription:
      "Découvrez une parenthèse de bonheur et de détente au cœur de la Bretagne. L'hôtel Restaurant et Spa Agapa vous accueille pour une déconnexion totale.",
    image: "/images/guirrec.webp",
    gallery: ["/images/unnamed.webp"],
    rating: 4.7,
    reviewCount: 1526,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "12 Rue des Bons Enfants, 22700 Perros-Guirec",
    phone: "02 96 49 01 10",
    email: "",
    website: "https://en.lagapa.com/",
  },
  {
    id: "14",
    slug: "best-western-les-bains-perros-guirec-hotel-et-spa",
    name: "Best Western Les Bains Perros-Guirec Hôtel et Spa",
    location: "Perros-Guirec, Côtes-d'Armor",
    city: "Perros-Guirec",
    department: "cotes-d-armor",
    departmentName: "Côtes-d'Armor",
    description: "Spa marin avec piscine chauffée, sauna et vues sur la côte.",
    fullDescription:
      "Au calme, juste derrière le front de mer, votre nouvel hôtel Best Western Les bains de Perros-Guirec Hotel et Spa vous propose des chambres modernes et spacieuses qui vous transportent dans le passé, comme dans les stations balnéaires des années 1950.",
    image: "/images/2020-11-04 (1).webp",
    gallery: ["/images/2020-11-04 (2).webp", "/images/unnamed (1).webp"],
    rating: 4.4,
    reviewCount: 828,
    priceRange: "€€",
    hours: "24h reception",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Sauna",
      "Salle de fitness",
      "Bar",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Massage", "Soins visage"],
    address: "100 Avenue du Casino, 22700 Perros-Guirec",
    phone: "02 96 91 22 11",
    email: "contact@hotel-les-bains-perros-guirec.fr",
    website: "https://www.hotel-les-bains-perros-guirec.fr/en",
  },
  {
    id: "15",
    slug: "grand-hotel-perros-guirec",
    name: "Grand Hôtel Perros-Guirec",
    location: "Perros-Guirec, Côtes-d'Armor",
    city: "Perros-Guirec",
    department: "cotes-d-armor",
    departmentName: "Côtes-d'Armor",
    description:
      "Hôtel-spa 4 étoiles sur la Côte de Granit Rose, avec piscine, hammam et soins thalasso.",
    fullDescription:
      "Le Grand Hôtel de Perros Guirec vue mer, sur la côte de Granit Rose en Bretagne. Restaurant bistronomique, Bar lounge, Spa sur le rooftop.",
    image: "/images/Casino-Grand-hotel-Perros-guirec.webp",
    gallery: [
      "/images/spa-sport-grand-hotel-perros-guirec.webp",
      "/images/spa-bas-grand-hotel-perros-guirec.webp",
    ],
    rating: 4.5,
    reviewCount: 481,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "45 Boulevard Joseph le Bihan, 22700 Perros-Guirec",
    phone: "02 96 49 80 80",
    email: "",
    website: "https://www.grandhotel-perrosguirec.com/",
  },
  // Ille-et-Vilaine
  {
    id: "16",
    slug: "les-thermes-marins-de-saint-malo-grand-hotel-des-thermes",
    name: "Les Thermes Marins de Saint-Malo (au Grand Hôtel des Thermes)",
    location: "Saint-Malo, Ille-et-Vilaine",
    city: "Saint-Malo",
    department: "ille-et-vilaine",
    departmentName: "Ille-et-Vilaine",
    description:
      "Thalasso légendaire avec piscine à jets, hammam et vues sur la plage.",
    fullDescription:
      "Hôtel 5* en face de la plage de Saint-Malo avec accès direct au centre de thalassothérapie comprenant un centre aquatonique, un spa et des restaurants.",
    image: "/images/2024-06-14.webp",
    gallery: [
      "/images/piscine-des-thermes-marins.webp",
      "/images/2024-06-13.webp",
      "/images/2024-06-13 (1).webp",
    ],
    rating: 4.6,
    reviewCount: 2914,
    priceRange: "€€€",
    hours: "8h30 - 20h",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine d'eau de mer",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: [
      "Thalassothérapie",
      "Enveloppement algues",
      "Massage relaxant",
      "Hydrojet",
      "Balnéothérapie",
      "Soins visage",
    ],
    address: "100 Boulevard Hébert, 35400 Saint-Malo",
    phone: "02 99 40 75 00",
    email: "info.hoteldesthermes@le-grand-hotel-des-thermes.fr",
    website: "https://www.le-grand-hotel-des-thermes.fr/en",
  },
  {
    id: "17",
    slug: "emeria-dinard-hotel-thalasso-spa",
    name: "EMERIA Dinard Hôtel Thalasso & Spa",
    location: "Dinard, Ille-et-Vilaine",
    city: "Dinard",
    department: "ille-et-vilaine",
    departmentName: "Ille-et-Vilaine",
    description:
      "Sur la Côte d'Émeraude, avec thalasso rénovée, piscine vue mer à 180° et soins innovants.",
    fullDescription:
      "Un institut de thalassothérapie et de spa de plus de 2800 m², 58 cabines de soins, des piscines d'eau de mer chauffées face à la mer, 2 restaurants et 1 bar.",
    image: "/images/unnamed (3).webp",
    gallery: ["/images/2024-04-16.webp", "/images/unnamed (2).webp"],
    rating: 4.3,
    reviewCount: 2358,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine d'eau de mer",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Thalassothérapie", "Massage", "Soins visage"],
    address: "1 Avenue du Château Hébert, 35800 Dinard",
    phone: "02 99 16 78 10",
    email: "",
    website: "https://www.emeriadinard.com/en",
  },
  {
    id: "18",
    slug: "hotel-le-nouveau-monde-saint-malo",
    name: "Hôtel Le Nouveau Monde Saint-Malo",
    location: "Saint-Malo, Ille-et-Vilaine",
    city: "Saint-Malo",
    department: "ille-et-vilaine",
    departmentName: "Ille-et-Vilaine",
    description: "Spa avec piscine à jets, hammam et solarium vue mer.",
    fullDescription:
      "Idéalement situé au cœur de Saint-Malo, face à la mer et à proximité de la vieille ville, le Nouveau Monde est un hôtel 4 étoiles de 83 chambres.",
    image: "/images/12.webp",
    gallery: [
      "/images/piscine-nouveau-monde-1200x750.jpg",
      "/images/hammam.jpg",
      "/images/PhilippeMeunierPhotographe_CR5_9396_R-2048x1366.jpg",
      "/images/unnamed (4).webp",
    ],
    rating: 4.7,
    reviewCount: 2525,
    priceRange: "€€€",
    hours: "",
    tags: ["Thalasso", "Piscine", "Vue mer"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Salle de fitness",
      "Restaurant",
      "Parking gratuit",
      "WiFi",
    ],
    treatments: ["Massage", "Soins visage"],
    address: "64 Chaussée du Sillon, 35400 Saint-Malo",
    phone: "02 99 40 40 00",
    email: "",
    website: "https://www.hotel-le-nouveau-monde.fr/en",
  },
  {
    id: "19",
    slug: "balthazar-hotel-spa-rennes",
    name: "Balthazar Hôtel & Spa Rennes",
    location: "Rennes, Ille-et-Vilaine",
    city: "Rennes",
    department: "ille-et-vilaine",
    departmentName: "Ille-et-Vilaine",
    description:
      "Spa Nuxe urbain avec bassin détente, jets hydromassants et ambiance sophistiquée.",
    fullDescription:
      "Bienvenue à l'hôtel Balthazar & Spa, un hôtel spa de luxe à Rennes, proposant des chambres modernes et élégantes, des installations de bien-être et d'affaires ainsi qu'un excellent restaurant sur place.",
    image: "/images/9170_ho_02_p_2048x1536.jpg",
    gallery: [
      "/images/unnamed (5).webp",
      "/images/unnamed (6).webp",
      "/images/9170_ho_05_p_2048x1536.jpg",
      "/images/9170_sp_00_p_2048x1536.jpg",
      "/images/9170_sp_01_p_2048x1536.jpg",
      "/images/9170_sp_05_p_2048x1536.jpg",
    ],
    rating: 4.7,
    reviewCount: 1588,
    priceRange: "€€€",
    hours: "",
    tags: ["Spa", "Piscine", "Urbain"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Restaurant",
      "Parking",
      "WiFi",
    ],
    treatments: ["Massage", "Soins visage"],
    address: "19 Rue Marechal Joffre, 35000 Rennes",
    phone: "02 99 32 32 32",
    email: "H9170@accor.com",
    website: "https://hotel-balthazar.com/en",
  },
  {
    id: "20",
    slug: "le-saint-antoine-hotel-et-spa-rennes",
    name: "Le Saint-Antoine Hôtel et Spa Rennes",
    location: "Rennes, Ille-et-Vilaine",
    city: "Rennes",
    department: "ille-et-vilaine",
    departmentName: "Ille-et-Vilaine",
    description:
      "Boutique-spa 4 étoiles avec bain à remous, sauna et soins premium.",
    fullDescription:
      "Hôtel boutique 4 étoiles situé en plein cœur de Rennes, Le Saint-Antoine BW Premier Collection Hotel & Spa allie confort et style dans un cadre résolument contemporain.",
    image: "/images/2022-07-15.webp",
    gallery: [
      "/images/unnamed (7).webp",
      "/images/2024-04-28.webp",
      "/images/unnamed (8).webp",
    ],
    rating: 4.3,
    reviewCount: 403,
    priceRange: "€€€",
    hours: "",
    tags: ["Spa", "Jacuzzi", "Urbain"],
    featured: false,
    amenities: [
      "Piscine chauffée",
      "Hammam",
      "Sauna",
      "Jacuzzi",
      "Salle de fitness",
      "Bar",
      "Parking",
      "WiFi",
    ],
    treatments: ["Massage", "Soins visage"],
    address: "27 Avenue Janvier, 35000 Rennes",
    phone: "02 23 44 33 33",
    email: "",
    website: "https://saint-antoine-hotel.fr/en",
  },
];

export function getSpaBySlug(slug: string): Spa | undefined {
  return spas.find((spa) => spa.slug === slug);
}

export function getSpasByDepartment(departmentId: string): Spa[] {
  return spas.filter((spa) => spa.department === departmentId);
}

export function getFeaturedSpas(): Spa[] {
  return spas.filter((spa) => spa.featured);
}

export function getDepartmentById(departmentId: string) {
  return departments.find((d) => d.id === departmentId);
}
